"""
Facebook job-group post classifier -> Supabase logger.

Takes a post (text and/or an image of a poster), classifies it as job/not-job,
extracts structured fields for job posts, and inserts a row into a Supabase
(Postgres) table. This is the multi-user-friendly version - the table lives
in the cloud, so any script/bot/dashboard for any group member can read from
and write to the same live data.

SETUP
-----
1. pip install anthropic supabase

2. LLM API key:
   export ANTHROPIC_API_KEY="sk-ant-..."

3. Supabase project (one-time, ~10 min):
   a. Go to https://supabase.com -> sign in with GitHub/Google -> "New project".
      Free tier is plenty for this (500MB DB, way more than you'll need).
   b. Once the project is created, go to Project Settings -> API.
      Copy the "Project URL" and the "anon public" key (or "service_role"
      key if you want this script to bypass row-level security - see note
      below). Set them as env vars:
        export SUPABASE_URL="https://xxxx.supabase.co"
        export SUPABASE_KEY="eyJ..."
   c. Go to the SQL Editor in the Supabase dashboard and run the CREATE TABLE
      statement below (also saved as schema.sql) to create the `job_posts`
      table.

   Note on keys: the "PUBLISHABLE" key respects Row Level Security (RLS) policies,
   which is what you want once multiple people/apps are reading and writing.
   For quick prototyping, either disable RLS on the table (fine while it's
   just you) or use the "SECRET" key (bypasses RLS entirely - keep
   this one secret, never put it in client-side/browser code).


USAGE
-----
    python job_post_classifier.py --text "Looking for a PA for a 2-day shoot..."
    python job_post_classifier.py --image path/to/poster.jpg
    python job_post_classifier.py --text "..." --image path/to/poster.jpg
    python job_post_classifier.py   # interactive mode, prompts for input
"""

import argparse
import base64
import json
import mimetypes
import os
import sys

from dotenv import load_dotenv 
from groq import Groq
from supabase import create_client, Client


# ----------------------------------------------------------------------------
# Config - edit these or set as environment variables
# ----------------------------------------------------------------------------
load_dotenv()

# Helper to enforce schema consistency

def _normalise_result(result: dict) -> dict:
    """Enforce that job‑specific fields are ``None`` when ``isjob`` is false.

    The function coerces ``isjob`` to a boolean and clears job‑related fields
    when the post is not a job posting.
    """
    # Coerce ``isjob`` to a bool (accepts ``True/False`` or ``"true"/"false"`` strings)
    raw = result.get("isjob")
    if isinstance(raw, str):
        isjob = raw.strip().lower() == "true"
    else:
        isjob = bool(raw)
    result["isjob"] = isjob

    # Fields that should be null when ``isjob`` is false
    job_fields = [
        "job_title",
        "job_type",
        "paid_status",
        "city",
        "state",
        "required_skills",
        "deadline",
    ]
    if not isjob:
        for key in job_fields:
            result[key] = None
    return result

SUPABASE_URL = st.secrets.get("SUPABASE_URL", "")
SUPABASE_KEY = st.secrets.get("SUPABASE_KEY", "")
TABLE_NAME = st.secrets.get("SUPABASE_TABLE", "")
GROQ_API_KEY = st.secrets.get("GROQ_API_KEY","")

VISION_MODEL = "qwen/qwen3.6-27b"   # currently the only model from groq that supports image as input
JSON_MODEL = "openai/gpt-oss-20b"

# prompt for step 1 model call
# should tell it to classify and output JSON, however JSON enforcement happens in step 2
STEP_1_SYSTEM_PROMPT = """You classify posts from a private Facebook job-board group. \
Respond ONLY with JSON, no markdown fences, no preamble, no commentary.

Schema:
{
  "isjob": "true" | "false",
  "job_type": "if isjob=true, one of: fashion show, modeling, acting, hosting, other",
  "post_type": "if isjob=false, one of: workshop info, update, warning, announcement, question, other. If job: null",
  "role": "job title, short, or null if not_job",
  "paid_status": "paid" | "unpaid" | "unclear" | null,
  "required_skills": any specific skills required e.g.: singing, instrument, etc. or null if nothing is required,
  "city": "city name or null DON'T INCLUDE STATE",
  "state": "abbreviated 2 letter United States name
  "deadline": "date string, or 'not stated', or null if not_job",
  "summary": "one plain-language sentence summarizing the post"
}

Only fill job_title/job_type/paid_status/city/state/required_skills/deadline when category "isjob"=true. \
For "isjob"=false posts, set those fields to null and fill post_type instead."""

# prompt for step 2 model call
STEP_2_SYSTEM_PROMPT = """You are a JSON formatter for Facebook job-board posts.
You will receive two messages:
1  The assistant message contains the raw description generated by a vision model.
2  (Optional) a later user message contains the original post text.

Your job is to produce JSON that conforms to the schema supplied via `response_format`.
Use the assistant message as the primary source. If any required field is missing,
refer to the user message for the missing information.
"""

# enforced via response_format parameter in step 2 model call
schema = {
  "type": "json_schema",
  "json_schema": {
    "name": "job_post_classification",
    "schema": {
      "type": "object",
      "properties": {
        "isjob": {
          "type": "boolean"
        },
        "job_type": {
          "type": ["string", "null"],
          "enum": ["fashion show", "modeling", "acting", "hosting", "other"]
        },
        "post_type": {
          "type": ["string", "null"],
          "enum": ["workshop info", "update", "warning", "announcement", "question", "other"]
        },
        "job_title": {
          "type": ["string", "null"]
        },
        "paid_status": {
          "type": ["string", "null"],
          "enum": ["paid", "unpaid", "unclear"]
        },
        "required_skills": {
          "type": ["string", "null"]
        },
        "city": {
          "type": ["string", "null"]
        },
        "state": {
          "type": ["string", "null"],
          "maxLength": 2,
          "pattern": "^[A-Za-z]{2}$"
        },
        "deadline": {
          "type": ["string", "null"]
        },
        "summary": {
          "type": "string"
        }
      },
      "required": [
        "isjob",
        "job_type",
        "post_type",
        "job_title",
        "paid_status",
        "required_skills",
        "city",
        "state",
        "deadline",
        "summary"
      ],
      "additionalProperties": False
    }
  }
}


# ----------------------------------------------------------------------------
# Classification
# ----------------------------------------------------------------------------

def classify_post(text: str | None, image_path: str | None, response_format: dict = schema) -> dict:
    """Classify a Facebook job-board post in two steps.

    Step 1: Call the Qwen vision model (``qwen/qwen3.6-27b``) to obtain a
    textual description of the post. The model accepts an optional image.

    Step 2: Pass the description (plus any original text) to the JSON-enforcing
    model ``openai/gpt-oss-20b``.

    The function returns a Python ``dict`` parsed from the JSON output.
    """
    client = Groq()

    # Build input for vision model (step 1)
    content_blocks: list[dict] = []
    if image_path:
        media_type = mimetypes.guess_type(image_path)[0] or "image/jpeg"
        with open(image_path, "rb") as f:
            image_b64 = base64.b64encode(f.read()).decode("utf-8")
        data_url = f"data:{media_type};base64,{image_b64}"
        content_blocks.append(
            {
                "type": "image_url",
                "image_url": {"url": data_url},
            }
        )
    user_text = text or "See attached image poster."
    content_blocks.append({"type": "text", "text": user_text})

    # Step 1 model call
    vision_response = client.chat.completions.create(
        model=VISION_MODEL,
        messages=[
            {"role": "system", "content": STEP_1_SYSTEM_PROMPT},
            {"role": "user", "content": content_blocks}
            ],
        temperature=0,
    )
    raw_vision = vision_response.choices[0].message.content
    if isinstance(raw_vision, list):
        vision_text = "".join(item.get("text", "") for item in raw_vision if item.get("type") == "text")
    else:
        vision_text = str(raw_vision)

    # Build messages for step‑2 JSON‑enforcement model
    json_messages = [
        {"role": "system", "content": STEP_2_SYSTEM_PROMPT},
        {"role": "assistant", "content": vision_text},
    ]
    if text:
        json_messages.append({"role": "user", "content": text})

    # Step 2 model call
    json_response = client.chat.completions.create(
        model=JSON_MODEL,
        messages=json_messages,
        response_format=response_format,
        temperature=0,
    )
    raw_json = json_response.choices[0].message.content
    cleaned = (
        raw_json.strip()
        .removeprefix("```json")
        .removeprefix("```")
        .removesuffix("```")
        .strip()
    )
    try:
        print(cleaned)
        result = json.loads(cleaned)
        return _normalise_result(result)
    except json.JSONDecodeError as e:
        raise ValueError(f"Model did not return valid JSON:\n{raw_json}") from e



# ----------------------------------------------------------------------------
# Supabase
# ----------------------------------------------------------------------------
def get_client() -> Client:
    if not SUPABASE_URL or not SUPABASE_KEY:
        raise RuntimeError(
            "SUPABASE_URL and SUPABASE_KEY must be set (env vars or in this script)."
        )
    return create_client(SUPABASE_URL, SUPABASE_KEY)


def insert_result(client: Client, result: dict, raw_text: str):
    row = {
        "isjob": result.get("isjob"),
        "job_type": result.get("job_type"),
        "post_type": result.get("post_type"),
        "job_title": result.get("job_title"),
        "paid_status": result.get("paid_status"),
        "required_skills": result.get("required_skills"),
        "city": result.get("city"),
        "state": result.get("state"),
        "deadline": result.get("deadline"),
        "summary": result.get("summary"),
        "raw_text": (raw_text or "")[:2000],
    }
    client.table(TABLE_NAME).insert(row).execute()




# ----------------------------------------------------------------------------
# CLI
# ----------------------------------------------------------------------------
def main():
    parser = argparse.ArgumentParser(description="Classify a FB group post and log it to Supabase.")
    parser.add_argument("--text", help="Post text")
    parser.add_argument("--image", help="Path to a poster image file")
    parser.add_argument("--no-db", action="store_true", help="Print result only, skip writing to Supabase")
    args = parser.parse_args()

    text, image_path = args.text, args.image

    if not text and not image_path:
        print("Paste post text (leave blank + press enter if image-only), then Enter:")
        text = input("> ").strip() or None
        image_path = input("Path to image (blank to skip): ").strip() or None

    if not text and not image_path:
        print("Nothing to classify. Provide --text and/or --image.")
        sys.exit(1)

    print("Classifying...")
    result = classify_post(text, image_path)
    print(json.dumps(result, indent=2))

    if args.no_db:
        return

    if not SUPABASE_URL or not SUPABASE_KEY:
        print("\nSUPABASE_URL / SUPABASE_KEY not set - skipping database write. "
              "See setup instructions at the top of this script.")
        return

    print("Writing to Supabase...")
    client = get_client()
    insert_result(client, result, text or "")
    print("Done.")


if __name__ == "__main__":
    main()

